name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # runs daily
  workflow_dispatch:   # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: jatinkmr
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake animation"
          add: "dist/*.svg"
